apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-docker-k8s-deployment
  namespace: tayakorn-springboot-docker-k8s
  labels:
    app: springboot-docker-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-docker-k8s
  template:
    metadata:
      labels:
        app: springboot-docker-k8s
    spec:
      containers:
      - name: springboot-docker-k8s
        image: springboot-docker-k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 8080